[package]
name = "tactus-o1-settlement-script"
version = "0.1.0"
edition = "2021"
rust-version = "1.92"
[workspace]
[patch.crates-io]
lazy_static = { path = "../vendor/lazy_static-1.5.1" }
[target.'cfg(target_arch = "riscv64")'.dependencies]
lazy_static = { version = "=1.5.1", features = ["ckb_single_thread"] }
[dependencies]
sp1-verifier = { version = "=6.8.1", default-features = false }
ckb-std = { version = "=0.15.3", default-features = false, features = ["ckb-types", "allocator"] }
[lib]
crate-type = ["staticlib", "rlib"]
[profile.release]
debug = false
panic = "abort"
