#!/usr/bin/env python3
"""Compare candidate execution with a separately built, pinned Geth t8n.

Usage: check-execution-geth.py /absolute/path/to/evm RUN_DIRECTORY
Candidates must first be generated by the execution-vectors Rust example.
"""
import hashlib
import json
from pathlib import Path
import subprocess
import sys


def write(path, value):
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def main():
    evm = Path(sys.argv[1]).resolve()
    directory = Path(sys.argv[2]).resolve()
    version = subprocess.check_output([str(evm), "--version"], text=True).strip()
    if version != "evm version 1.17.8-stable":
        raise ValueError(f"expected pinned Geth 1.17.8, got {version}")
    candidates = json.loads((directory / "candidates.json").read_text())
    results = []
    block_count = 0
    for case in candidates["cases"]:
        case_dir = directory / case["name"]
        case_dir.mkdir(exist_ok=True)
        prestate = case_dir / "genesis-alloc.json"
        write(prestate, case["alloc"])
        block_results = []
        for number, block in enumerate(case["blocks"], 1):
            output = case_dir / str(number)
            output.mkdir(exist_ok=True)
            write(output / "env.json", block["env"])
            write(output / "txs.json", block["txs"])
            cmd = [str(evm), "t8n", "--state.fork", "Shanghai", "--state.chainid", "31337", "--state.reward", "-1", "--input.alloc", str(prestate), "--input.env", str(output / "env.json"), "--input.txs", str(output / "txs.json"), "--output.basedir", str(output), "--output.alloc", "post-alloc.json", "--output.result", "result.json", "--output.body", "body.rlp"]
            process = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            (output / "stdout.log").write_text(process.stdout)
            (output / "stderr.log").write_text(process.stderr)
            if process.returncode:
                raise RuntimeError(f"{case['name']} block {number}: {process.stderr}")
            result = json.loads((output / "result.json").read_text())
            expected = block["expected"]
            header = expected["header"]
            for actual_field, expected_field in [("stateRoot", "stateRoot"), ("txRoot", "transactionsRoot"), ("receiptsRoot", "receiptsRoot"), ("logsBloom", "logsBloom"), ("gasUsed", "gasUsed")]:
                actual, wanted = result[actual_field], header[expected_field]
                if actual_field == "gasUsed":
                    actual, wanted = int(str(actual), 0), int(str(wanted), 0)
                if actual != wanted:
                    raise AssertionError(f"{case['name']} block {number} {actual_field}: {actual} != {wanted}")
            rejected = [entry["index"] for entry in result.get("rejected", [])]
            wanted_rejected = [index for index, outcome in enumerate(expected["outcomes"]) if outcome["transaction_index"] is None]
            if rejected != wanted_rejected:
                raise AssertionError(f"rejection indices: {rejected} != {wanted_rejected}")
            accepted = [o for o in expected["outcomes"] if o["transaction_index"] is not None]
            if len(result["receipts"]) != len(accepted):
                raise AssertionError("receipt count mismatch")
            for receipt, outcome in zip(result["receipts"], accepted):
                if int(receipt["gasUsed"], 0) != outcome["gas_used"] or int(receipt["status"], 0) != int(outcome["status"] == "Success"):
                    raise AssertionError("receipt status or individual gas mismatch")
            block_results.append(result)
            block_count += 1
            prestate = output / "post-alloc.json"
        results.append({"name": case["name"], "genesis": case["genesis"], "batch": case["batch"], "geth": block_results})
    artifact = {"schema": 1, "geth_version": version, "geth_binary_sha256": hashlib.sha256(evm.read_bytes()).hexdigest(), "rules_hash": candidates["rules_hash"], "case_count": len(results), "block_count": block_count, "cases": results}
    if len(sys.argv) > 3:
        reference = json.loads(Path(sys.argv[3]).read_text())
        for field in ["rules_hash", "case_count", "block_count", "cases"]:
            if artifact[field] != reference[field]:
                raise AssertionError(f"independent result differs from checked-in {field}")
    write(directory / "verified.json", artifact)
    print(f"Geth independent comparison passed: {len(results)} cases, {block_count} blocks")


if __name__ == "__main__":
    main()
